#!/bin/bash
set -ex

for version in 2.0 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8; do
    docker image build \
        --build-arg VERSION="$version" \
        --tag "$DOCKER_REPO:ansible-$version" \
        --target "ansible-$version" \
        .
done